### ISSUE TITLE
Parameters missing from oat_matrix

### ISSUE THREAD

**Issue by AmeliePzk** [oie-mines-paristech/lca_algebraic#48]
Hello,

I stumbled upon an issue with the OAT analysis. I defined eleven parameters for my model, seven enum and five float. While they all appear in the list (list_parameters()), only four of them (all of the type float) are considered in the OAT analysis. (The one float parameter missing is one I defined through four others, since it is a share and the sum of all five should not exceed 1) 
Are there maybe any common mistakes coming to mind, which could lead to this issue? 
In another project, the enum parameters work just fine (so far, I exclusively have enum parameters there).

Thank you in advance!

**Comment by raphaeljolivet** [comment]
Hi, 

Can you tell more ? 
What version of lca_algebraic are you using ? 

Maybe you could share the code (privately possibly ?) 


De: "AmeliePzk" ***@***.***> 
À: "oie-mines-paristech/lca_algebraic" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Envoyé: Mardi 23 Avril 2024 13:17:34 
Objet: [oie-mines-paristech/lca_algebraic] Parameters missing from oat_matrix (Issue #48) 





Hello, 

I stumbled upon an issue with the OAT analysis. I defined eleven parameters for my model, seven enum and five float. While they all appear in the list (list_parameters()), only four of them (all of the type float) are considered in the OAT analysis. (The one float parameter missing is one I defined through four others, since it is a share and the sum of all five should not exceed 1) 
Are there maybe any common mistakes coming to mind, which could lead to this issue? 
In another project, the enum parameters work just fine (so far, I exclusively have enum parameters there). 

Thank you in advance!
